CREATE TABLE IF NOT EXISTS RATING (
                         ID SERIAL PRIMARY KEY,
                         NAME VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS (
                         ID BIGSERIAL PRIMARY KEY,
                         NAME VARCHAR(200) NOT NULL,
                         DESCRIPTION VARCHAR(200) NOT NULL,
                         RELEASE_DATE DATE NOT NULL,
                         DURATION INTEGER NOT NULL,
                         RATING_ID INTEGER NOT NULL,
                         RATE REAL NOT NULL,
                         CONSTRAINT FILMS_RATING_ID_FK FOREIGN KEY (RATING_ID) REFERENCES RATING(ID)
);

CREATE INDEX IF NOT EXISTS FILMS_RATING_ID_FK_INDEX ON FILMS(RATING_ID);

CREATE TABLE IF NOT EXISTS GENRES (
                         ID SERIAL PRIMARY KEY,
                         NAME VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
                         FILM_ID BIGINT NOT NULL,
                         GENRE_ID INTEGER NOT NULL,
                         CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID, GENRE_ID),
                         CONSTRAINT FILM_GENRE_FILM_ID_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID) ON DELETE CASCADE,
                         CONSTRAINT FILM_GENRE_GENRE_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS FILM_GENRE_FILM_ID_FK_INDEX ON FILM_GENRE(FILM_ID);
CREATE INDEX IF NOT EXISTS FILM_GENRE_GENRE_ID_FK_INDEX ON FILM_GENRE(GENRE_ID);

CREATE TABLE IF NOT EXISTS DIRECTORS (
                         ID BIGSERIAL PRIMARY KEY,
                         NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_DIRECTOR (
                         FILM_ID INTEGER NOT NULL,
                         DIRECTOR_ID INTEGER NOT NULL,
                         CONSTRAINT FILM_DIRECTOR_FILM_ID_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID) ON DELETE CASCADE,
                         CONSTRAINT FILM_DIRECTOR_DIRECTOR_ID_FK FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTORS(ID) ON DELETE CASCADE,
                         CONSTRAINT FILM_ID_DIRECTOR_ID PRIMARY KEY (FILM_ID,DIRECTOR_ID)
);

CREATE INDEX IF NOT EXISTS FILM_DIRECTOR_DIRECTOR_ID_FK_INDEX ON FILM_DIRECTOR(DIRECTOR_ID);
CREATE INDEX IF NOT EXISTS FILM_DIRECTOR_FILM_ID_FK_INDEX ON FILM_DIRECTOR(FILM_ID);