server:
  port: 8088
spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: http://localhost:8084
      request-read-timeout: 5000
      request-connect-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

urls:
  recommendationsClient: localhost:8082

springdoc:
  api-docs:
    path: /users/api-docs
  swagger-ui:
    path: /users/swagger-ui.html
    enabled: true