CREATE TABLE USERS (
                    USER_ID BIGSERIAL PRIMARY KEY,
                    EMAIL VARCHAR(30) NOT NULL,
                    LOGIN VARCHAR(30) NOT NULL,
                    NAME VARCHAR(30),
                    BIRTHDAY DATE
);

CREATE TABLE FRIENDS (
                    USER_ID BIGINT NOT NULL,
                    FRIEND_ID BIGINT NOT NULL,
                    CONSTRAINT FRIENDS_USER_ID_FRIEND_ID_PK PRIMARY KEY (USER_ID,FRIEND_ID),
                    CONSTRAINT FRIENDS_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
                    CONSTRAINT FRIENDS_FRIEND_ID_FK FOREIGN KEY (FRIEND_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE INDEX FRIENDS_USER_ID_FK_INDEX ON FRIENDS(USER_ID);
CREATE INDEX FRIENDS_FRIEND_ID_FK_INDEX ON FRIENDS(FRIEND_ID);