CREATE TABLE IF NOT EXISTS EVENTS (
                    EVENT_ID BIGSERIAL PRIMARY KEY,
                    TIMESTAMP BIGINT NOT NULL,
                    USER_ID INTEGER NOT NULL,
                    EVENT_TYPE VARCHAR(11) NOT NULL,
                    OPERATION VARCHAR(11) NOT NULL,
                    ENTITY_ID INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS EVENTS_USERS_ID_FK_INDEX ON EVENTS(USER_ID);