server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: ru.aasmc.filmservice.dto.FilmRateDto
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/filmorate_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

kafkaprops:
  filmLikeTopic: "filmLikes"
  deleteAllLikesTopic: "deleteAllLikes"
  newRatingTopic: "newRatings"

urls:
  userService: localhost:8088

springdoc:
  api-docs:
    path: /films/api-docs
  swagger-ui:
    path: /films/swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"