server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/filmorate_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"