server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  cloud:
    gateway:
      discovery:
        # automated mapping of routes via Eureka Service Discovery
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: film-service
          uri: lb://film-service
          predicates:
            - Path=/films/**, /directors/**, /genres/**, /mpa/**
          filters:
            - RemoveRequestHeader= Cookie, Set-Cookie
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader= Cookie, Set-Cookie
        - id: reviews-service
          uri: lb://reviews-service
          predicates:
            - Path=/reviews/**
          filters:
            - RemoveRequestHeader= Cookie, Set-Cookie
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/rating/**
          filters:
            - RemoveRequestHeader= Cookie, Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: "*"


