server:
  port: 8090
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: ${spring.application.name}
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: ru.aasmc.ratingservice.dto.FilmLikeDto

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      replica-set-name: "rs0"
#      uri: mongodb://localhost:27017/?connect=direct&replicaSet=singleNodeReplSet&readPreference=primary
#      database: filmorate-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5437/filmorate_rating
    username: postgres
    password: '{cipher}7ae9c6ddf90efd4b907056ea390955641bd58ab29491025f4b596d83fcfaf01c'
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

kafkaprops:
  filmLikeTopic: "filmLikes"
  deleteAllLikesTopic: "deleteAllLikes"
  newRatingTopic: "newRatings"
  bootstrapServers: ${spring.kafka.bootstrap-servers}
  clientId: ${spring.kafka.client-id}
  autoOffsetReset: earliest

springdoc:
  api-docs:
    path: /rating/api-docs
  swagger-ui:
    path: /rating/swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"