eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5431/filmorate_user
    username: postgres
    password: {cipher} 7ae9c6ddf90efd4b907056ea390955641bd58ab29491025f4b596d83fcfaf01c
    driver-class-name: org.postgresql.Driver

kafkaprops:
  userFriendTopic: "userFriends"

urls:
  recommendationsClient: localhost:8082
  eventService: localhost:8091

springdoc:
  api-docs:
    path: /users/api-docs
  swagger-ui:
    path: /users/swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"