spring:
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5431/filmorate_user
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5431/filmorate_user